import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

describe('generated scipy wrapper (opportunistic)', () => {
  const generatedPath = join(process.cwd(), 'generated', 'scipy.generated.ts');

  it('exists and contains the standard header and module tag', () => {
    if (!existsSync(generatedPath)) {
      console.warn(
        '[skip] generated/scipy.generated.ts not found; run `npm run matrix` to create it'
      );
      expect(true).toBe(true);
      return;
    }
    const content = readFileSync(generatedPath, 'utf-8');
    expect(content).toContain('Generated by tywrap');
    expect(content).toContain('// Module: scipy');
  });
});
