import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// This test is opportunistic: it runs only if the pydantic wrapper has been generated
// by the matrix harness (npm run matrix). In CI or environments without that file,
// the test is skipped and does not fail the suite.

describe('generated pydantic wrapper (opportunistic)', () => {
  const generatedPath = join(process.cwd(), 'generated', 'pydantic.generated.ts');

  it('exists and contains the standard header and module tag', () => {
    if (!existsSync(generatedPath)) {
      // Skip when not present

      console.warn(
        '[skip] generated/pydantic.generated.ts not found; run `npm run matrix` to create it'
      );
      expect(true).toBe(true);
      return;
    }
    const content = readFileSync(generatedPath, 'utf-8');
    expect(content).toContain('Generated by tywrap');
    expect(content).toContain('// Module: pydantic');
  });
});





