import { describe, it, expect } from 'vitest';
import { mkdtemp, rm, writeFile, mkdir } from 'node:fs/promises';
import { delimiter, join } from 'node:path';
import { tmpdir } from 'node:os';
import { generate } from '../src/tywrap.js';
import { processUtils, fsUtils } from '../src/utils/runtime.js';
import { NodeBridge } from '../src/runtime/node.js';
import { getDefaultPythonPath } from '../src/utils/python.js';

/**
 * IR-only Integration Tests
 */
const isCi =
  ['1', 'true'].includes((process.env.CI ?? '').toLowerCase()) ||
  ['1', 'true'].includes((process.env.GITHUB_ACTIONS ?? '').toLowerCase()) ||
  ['1', 'true'].includes((process.env.ACT ?? '').toLowerCase());
const nodeBridgeTimeoutMs = isCi ? 60000 : 30000;
const nodeBridgeTestTimeoutMs = isCi ? 60000 : 30000;
const defaultPythonPath = getDefaultPythonPath();

describe('IR-only integration', () => {
  it('tywrap_ir emits JSON IR for math', async () => {
    const result = await processUtils.exec(defaultPythonPath, [
      '-m',
      'tywrap_ir',
      '--module',
      'math',
      '--no-pretty',
    ]);
    expect(result.code).toBe(0);
    const json = JSON.parse(result.stdout);
    expect(json.module).toBe('math');
    expect(Array.isArray(json.functions)).toBe(true);
  });

  it('generate() writes TS for math and contains wrappers', async () => {
    const outDir = './generated';
    const res = await generate({
      pythonModules: { math: { runtime: 'node', typeHints: 'strict' } },
      output: { dir: outDir, format: 'esm', declaration: false, sourceMap: false },
      runtime: { node: { pythonPath: defaultPythonPath } },
      performance: { caching: false, batching: false, compression: 'none' },
      development: { hotReload: false, sourceMap: false, validation: 'none' },
    } as any);
    expect(res.written.some(p => p.endsWith('math.generated.ts'))).toBe(true);
    const content = await fsUtils.readFile(`${outDir}/math.generated.ts`);
    expect(content).toContain('Generated by tywrap');
    expect(content).toContain('export async function');
    expect(content).toContain("getRuntimeBridge().call('math', 'sqrt'");
  });

  it('supports local Python modules via pythonImportPath', async () => {
    const tempDir = await mkdtemp(join(tmpdir(), 'tywrap-pythonImportPath-'));
    try {
      const importDir = join(tempDir, 'py');
      await mkdir(importDir, { recursive: true });
      await writeFile(
        join(importDir, 'local_module.py'),
        `def add(a: int, b: int) -> int:\n  return a + b\n\n# Should be excluded by default export filtering\ndef dataclass(x):\n  return x\n`,
        'utf-8'
      );

      const outDir = join(tempDir, 'generated');
      const res = await generate({
        pythonModules: { local_module: { runtime: 'node', typeHints: 'strict' } },
        pythonImportPath: [importDir],
        output: { dir: outDir, format: 'esm', declaration: false, sourceMap: false },
        runtime: { node: { pythonPath: defaultPythonPath } },
        performance: { caching: false, batching: false, compression: 'none' },
        development: { hotReload: false, sourceMap: false, validation: 'none' },
      } as any);

      expect(res.written.some(p => p.endsWith('local_module.generated.ts'))).toBe(true);
      const content = await fsUtils.readFile(join(outDir, 'local_module.generated.ts'));
      expect(content).toContain('local_module');
      expect(content).toContain('add');
      expect(content).not.toContain("call('local_module', 'dataclass'");
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  }, 30_000);

  it('check mode bypasses stale IR cache when caching is enabled', async () => {
    const tempDir = await mkdtemp(join(tmpdir(), 'tywrap-check-cache-'));
    const originalCwd = process.cwd();
    const originalPythonPath = process.env.PYTHONPATH;
    try {
      const importDir = join(tempDir, 'py');
      await mkdir(importDir, { recursive: true });
      const modulePath = join(importDir, 'local_stale_cache.py');
      await writeFile(modulePath, `def stable_value() -> int:\n  return 1\n`, 'utf-8');

      process.chdir(tempDir);
      const repoTywrapIr = join(originalCwd, 'tywrap_ir');
      process.env.PYTHONPATH = originalPythonPath
        ? `${repoTywrapIr}${delimiter}${originalPythonPath}`
        : repoTywrapIr;

      const options = {
        pythonModules: { local_stale_cache: { runtime: 'node', typeHints: 'strict' as const } },
        pythonImportPath: [importDir],
        output: {
          dir: join(tempDir, 'generated'),
          format: 'esm' as const,
          declaration: false,
          sourceMap: false,
        },
        runtime: { node: { pythonPath: defaultPythonPath } },
        performance: { caching: true, batching: false, compression: 'none' as const },
        development: { hotReload: false, sourceMap: false, validation: 'none' as const },
      };

      const firstRun = await generate(options as any);
      const generatedTsPath = firstRun.written.find(p => p.endsWith('.generated.ts'));
      expect(typeof generatedTsPath).toBe('string');

      await writeFile(
        modulePath,
        `def stable_value() -> int:\n  return 1\n\ndef added_after_first_run() -> int:\n  return 2\n`,
        'utf-8'
      );

      const checkResult = await generate(options as any, { check: true });
      expect((checkResult.outOfDate ?? []).includes(generatedTsPath as string)).toBe(true);
    } finally {
      process.env.PYTHONPATH = originalPythonPath;
      process.chdir(originalCwd);
      await rm(tempDir, { recursive: true, force: true });
    }
  }, 30_000);

  it('generate() emits valid TypeScript for advanced typing fixtures', async () => {
    const tempDir = await mkdtemp(join(process.cwd(), '.tmp-advanced-types-'));
    try {
      const outDir = join(tempDir, 'generated');
      const res = await generate({
        pythonModules: { advanced_types: { runtime: 'node', typeHints: 'strict' } },
        pythonImportPath: ['test/fixtures/python'],
        output: { dir: outDir, format: 'esm', declaration: false, sourceMap: false },
        runtime: { node: { pythonPath: defaultPythonPath } },
        performance: { caching: false, batching: false, compression: 'none' },
        development: { hotReload: false, sourceMap: false, validation: 'none' },
      } as any);

      expect(res.written.some(p => p.endsWith('advanced_types.generated.ts'))).toBe(true);

      const generatedPath = join(outDir, 'advanced_types.generated.ts');
      const tscPath = join(process.cwd(), 'node_modules', 'typescript', 'lib', 'tsc.js');
      const compile = await processUtils.exec(
        process.execPath,
        [
          tscPath,
          '--noEmit',
          '--pretty',
          'false',
          '--target',
          'ES2022',
          '--lib',
          'ES2022,DOM,DOM.Iterable',
          '--module',
          'ESNext',
          '--moduleResolution',
          'bundler',
          '--skipLibCheck',
          generatedPath,
        ],
        { cwd: process.cwd(), timeoutMs: 30_000 }
      );

      expect(compile.code).toBe(0);
      expect(compile.stderr).toBe('');
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  }, 30_000);
});

describe('NodeBridge smoke', () => {
  it(
    'calls math.sqrt',
    async () => {
      const bridge = new NodeBridge({
        scriptPath: 'runtime/python_bridge.py',
        timeoutMs: nodeBridgeTimeoutMs,
      });
      const result = await bridge.call<number>('math', 'sqrt', [9]);
      expect(result).toBe(3);
      await bridge.dispose();
    },
    nodeBridgeTestTimeoutMs
  );
});
